# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ./mainwindow.h \
    ./mdichild.h \
    ./highlighter.h
SOURCES += ./main.cpp \
    ./mainwindow.cpp \
    ./mdichild.cpp \
    ./highlighter.cpp
RESOURCES += mdi.qrc
